In [1]:
import pandas as pd
import numpy as np

In [2]:
true = pd.read_csv('True.csv')

In [3]:
fake = pd.read_csv('Fake.csv')

In [4]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [6]:
true['label']=1

In [7]:
fake['label'] = 0

In [8]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [9]:
fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [10]:
news = pd.concat([fake,true],axis=0)

In [11]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [12]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [13]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [14]:
news = news.drop(['title','subject','date'],axis=1)

In [15]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [16]:
news = news.sample(frac=1)

In [17]:
news.head()

                                                    text  label
430    WASHINGTON (Reuters) - U.S. Defense Secretary ...      1
1315   WASHINGTON (Reuters) - The Republican chairman...      1
15277  BEIJING (Reuters) - Taiwan is the most importa...      1
1156   SAN FRANCISCO (Reuters) - A U.S. federal judge...      1
13296  DAR ES SALAAM (Reuters) - Police in Tanzania h...      1

In [18]:
news.reset_index(inplace=True)

In [19]:
news.head()

   index                                               text  label
0    430  WASHINGTON (Reuters) - U.S. Defense Secretary ...      1
1   1315  WASHINGTON (Reuters) - The Republican chairman...      1
2  15277  BEIJING (Reuters) - Taiwan is the most importa...      1
3   1156  SAN FRANCISCO (Reuters) - A U.S. federal judge...      1
4  13296  DAR ES SALAAM (Reuters) - Police in Tanzania h...      1

In [20]:
news.drop(['index'],axis=1, inplace = True)

In [21]:
news.head()

                                                text  label
0  WASHINGTON (Reuters) - U.S. Defense Secretary ...      1
1  WASHINGTON (Reuters) - The Republican chairman...      1
2  BEIJING (Reuters) - Taiwan is the most importa...      1
3  SAN FRANCISCO (Reuters) - A U.S. federal judge...      1
4  DAR ES SALAAM (Reuters) - Police in Tanzania h...      1

In [22]:
import re

In [23]:
def wordopt(text):
    text = text.lower()

    text = re.sub(r'https?://\S+|www\.\S+','',text)

    text = re.sub(r'[^\w\s]','',text)

    text = re.sub(r'\d','',text)

    text = re.sub(r'\n','',text)

    return text

In [24]:
news['text'] = news['text'].apply(wordopt)

In [25]:
news['text']

0        washington reuters  us defense secretary jim m...
1        washington reuters  the republican chairman of...
2        beijing reuters  taiwan is the most important ...
3        san francisco reuters  a us federal judge said...
4        dar es salaam reuters  police in tanzania have...
                               ...
44893    moscow reuters  an official document seen by r...
44894    there s really no better person to roast sarah...
44895    washington reuters  republican presidential ca...
44896    the truth in the information below is so dead ...
44897    donald trump just unleashed an attack on any a...
Name: text, Length: 44898, dtype: object

In [26]:
x = news['text']
y = news['label']

In [27]:
x

0        washington reuters  us defense secretary jim m...
1        washington reuters  the republican chairman of...
2        beijing reuters  taiwan is the most important ...
3        san francisco reuters  a us federal judge said...
4        dar es salaam reuters  police in tanzania have...
                               ...
44893    moscow reuters  an official document seen by r...
44894    there s really no better person to roast sarah...
44895    washington reuters  republican presidential ca...
44896    the truth in the information below is so dead ...
44897    donald trump just unleashed an attack on any a...
Name: text, Length: 44898, dtype: object

In [28]:
y

0        1
1        1
2        1
3        1
4        1
        ..
44893    1
44894    0
44895    1
44896    0
44897    0
Name: label, Length: 44898, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [31]:
x_train.shape

(31428,)

In [32]:
x_test.shape

(13470,)

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
vectorization = TfidfVectorizer()

In [35]:
xv_train = vectorization.fit_transform(x_train)

In [36]:
xv_test = vectorization.transform(x_test)

In [37]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6446328 stored elements and shape (31428, 174552)>

In [38]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2733935 stored elements and shape (13470, 174552)>

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
LR = LogisticRegression()

In [41]:
LR.fit(xv_train, y_train)

LogisticRegression()

In [42]:
pred_lr = LR.predict(xv_test)

In [43]:
LR.score(xv_test, y_test)

0.9876763177431329

In [44]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [45]:
print(classification_report(y_test, pred_lr))
print("Accuracy:", accuracy_score(y_test, pred_lr))
print(confusion_matrix(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7081
           1       0.98      0.99      0.99      6389

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

Accuracy: 0.9876763177431329
[[6983   98]
 [  68 6321]]

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
DTC = DecisionTreeClassifier()

In [48]:
DTC.fit(xv_train, y_train)

DecisionTreeClassifier()

In [49]:
pred_dtc = DTC.predict(xv_test)

In [50]:
DTC.score(xv_test, y_test)

0.9962880475129918

In [51]:
print(classification_report(y_test, pred_dtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7081
           1       1.00      1.00      1.00      6389

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
rfc = RandomForestClassifier()

In [54]:
rfc.fit(xv_train, y_train)

RandomForestClassifier()

In [55]:
predict_rfc = rfc.predict(xv_test)

In [56]:
rfc.score(xv_test, y_test)

0.987750556792873

In [57]:
print(classification_report(y_test, predict_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7081
           1       0.99      0.99      0.99      6389

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [58]:
from sklearn.ensemble import GradientBoostingClassifier

In [59]:
gbc = GradientBoostingClassifier()

In [60]:
gbc.fit(xv_train, y_train)

GradientBoostingClassifier()

In [61]:
pred_gbc = gbc.predict(xv_test)

In [62]:
gbc.score(xv_test, y_test)

0.9956198960653304

In [63]:
print(classification_report(y_test, pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7081
           1       0.99      1.00      1.00      6389

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [64]:
def output_label(n):
    if n==0:
        return "It is a Fake News"
    elif n == 1:
        return "It is a Genuine News"

In [65]:



def manual_testing(news):
    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)

    # Apply the same cleaning used during training
    new_def_test["text"] = new_def_test["text"].apply(wordopt)

    # Transform using the SAME vectorizer used for training
    new_xv_test = vectorization.transform(new_def_test["text"])

    pred_lr = LR.predict(new_xv_test)
    pred_dt = DTC.predict(new_xv_test)
    pred_gbc = gbc.predict(new_xv_test)
    pred_rfc = rfc.predict(new_xv_test)

    return (
        "\n\nLR Prediction: {}"
        "\nDT Prediction: {}"
        "\nGBC Prediction: {}"
        "\nRFC Prediction: {}"
    ).format(
        output_label(pred_lr[0]),
        output_label(pred_dt[0]),
        output_label(pred_gbc[0]),
        output_label(pred_rfc[0])
    )

In [66]:
news_article = str(input())

 SEATTLE/WASHINGTON (Reuters) - President Donald Trump called on the U.S. Postal Service on Friday to charge â€œmuch moreâ€ to ship packages for Amazon (AMZN.O), picking another fight with an online retail giant he has criticized in the past.     â€œWhy is the United States Post Office, which is losing many billions of dollars a year, while charging Amazon and others so little to deliver their packages, making Amazon richer and the Post Office dumber and poorer? Should be charging MUCH MORE!â€ Trump wrote on Twitter.  The presidentâ€™s tweet drew fresh attention to the fragile finances of the Postal Service at a time when tens of millions of parcels have just been shipped all over the country for the holiday season.  The U.S. Postal Service, which runs at a big loss, is an independent agency within the federal government and does not receive tax dollars for operating expenses, according to its website.  Package delivery has become an increasingly important part of its business as the Internet has led to a sharp decline in the amount of first-class letters. The president does not determine postal rates. They are set by the Postal Regulatory Commission, an independent government agency with commissioners selected by the president from both political parties. That panel raised prices on packages by almost 2 percent in November.  Amazon was founded by Jeff Bezos, who remains the chief executive officer of the retail company and is the richest person in the world, according to Bloomberg News. Bezos also owns The Washington Post, a newspaper Trump has repeatedly railed against in his criticisms of the news media. In tweets over the past year, Trump has said the â€œAmazon Washington Postâ€ fabricated stories. He has said Amazon does not pay sales tax, which is not true, and so hurts other retailers, part of a pattern by the former businessman and reality television host of periodically turning his ire on big American companies since he took office in January. Daniel Ives, a research analyst at GBH Insights, said Trumpâ€™s comment could be taken as a warning to the retail giant. However, he said he was not concerned for Amazon. â€œWe do not see any price hikes in the future. However, that is a risk that Amazon is clearly aware of and (it) is building out its distribution (system) aggressively,â€ he said. Amazon has shown interest in the past in shifting into its own delivery service, including testing drones for deliveries. In 2015, the company spent $11.5 billion on shipping, 46 percent of its total operating expenses that year.  Amazon shares were down 0.86 percent to $1,175.90 by early afternoon. Overall, U.S. stock prices were down slightly on Friday.  Satish Jindel, president of ShipMatrix Inc, which analyzes shipping data, disputed the idea that the Postal Service charges less than United Parcel Service Inc (UPS.N) and FedEx Corp (FDX.N), the other biggest players in the parcel delivery business in the United States. Many customers get lower rates from UPS and FedEx than they would get from the post office for comparable services, he said. The Postal Service delivers about 62 percent of Amazon packages, for about 3.5 to 4 million a day during the current peak year-end holiday shipping season, Jindel said. The Seattle-based company and the post office have an agreement in which mail carriers take Amazon packages on the last leg of their journeys, from post offices to customersâ€™ doorsteps. Amazonâ€™s No. 2 carrier is UPS, at 21 percent, and FedEx is third, with 8 percent or so, according to Jindel. Trumpâ€™s comment tapped into a debate over whether Postal Service pricing has kept pace with the rise of e-commerce, which has flooded the mail with small packages.Private companies like UPS have long claimed the current system unfairly undercuts their business. Steve Gaut, a spokesman for UPS, noted that the company values its â€œproductive relationshipâ€ with the postal service, but that it has filed with the Postal Regulatory Commission its concerns about the postal serviceâ€™s methods for covering costs. Representatives for Amazon, the White House, the U.S. Postal Service and FedEx declined comment or were not immediately available for comment on Trumpâ€™s tweet. According to its annual report, the Postal Service lost $2.74 billion this year, and its deficit has ballooned to $61.86 billion.  While the Postal Serviceâ€™s revenue for first class mail, marketing mail and periodicals is flat or declining, revenue from package delivery is up 44 percent since 2014 to $19.5 billion in the fiscal year ended Sept. 30, 2017. But it also lost about $2 billion in revenue when a temporary surcharge expired in April 2016. According to a Government Accountability Office report in February, the service is facing growing personnel expenses, particularly $73.4 billion in unfunded pension and benefits liabilities. The Postal Service has not announced any plans to cut costs. By law, the Postal Service has to set prices for package delivery to cover the costs attributable to that service. But the postal service allocates only 5.5 percent of its total costs to its business of shipping packages even though that line of business is 28 percent of its total revenue.

In [71]:
manual_testing(news_article)

'\n\nLR Prediction: It is a Genuine News\nDT Prediction: It is a Genuine News\nGBC Prediction: It is a Genuine News\nRFC Prediction: It is a Genuine News'